import { Toaster } from "@/components/ui/sonner";
import {
	DEFAULT_LOCALE,
	LOCALE_COOKIE,
	getTextDirection,
} from "@/lib/i18n/config";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import Providers from "./providers";
import { useSwitchLocale } from "@/lib/i18n/use-switch-locale";

const publicSans = Public_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const jar = await cookies();
	const locale = jar.get(LOCALE_COOKIE)?.value ?? DEFAULT_LOCALE;
	const dir = getTextDirection(locale);
	
	return (
		<html lang={locale} className={publicSans.variable} dir={dir}>
			{/* <Script
				src="//unpkg.com/react-scan/dist/auto.global.js"
				crossOrigin="anonymous"
				strategy="beforeInteractive"
			/> */}
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Toaster />
				<NextTopLoader
					color="var(--primary)"
					shadow={false}
					showSpinner={false}
				/>
				<Providers dir={dir}>{children}</Providers>
			</body>
		</html>
	);
}
