import NextTopLoader from "nextjs-toploader";
import { DirectionProvider } from "@/components/ui/direction";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";

const publicSans = Public_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={publicSans.variable}>
			{/* <Script
				src="//unpkg.com/react-scan/dist/auto.global.js"
				crossOrigin="anonymous"
				strategy="beforeInteractive"
			/> */}
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Toaster />
				<NextTopLoader color="var(--primary)" />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
